name: yuncker.com
favicon: null
layout_spectrum: 0.9741193426307291
typography_spectrum: 0.8407876552082598
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7446960508823395
  lightness: 0.9537281191442162
  saturation: 0.5348895273637027
  rhythmicContrast: 0.15725084044970572
purpose: []
