name: yuncker.com
favicon: null
layout_spectrum: 0.2505
typography_spectrum: 0.24451
title: Paul Yuncker
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.125
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
